define("ember-cli-mirage/server", ["exports", "@miragejs/server", "ember-cli-mirage/ember-data", "ember-cli-mirage/utils/ember-data"], function (_exports, _server, _emberData, _emberData2) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  Object.defineProperty(_exports, "defaultPassthroughs", {
    enumerable: true,
    get: function () {
      return _server.defaultPassthroughs;
    }
  });
  _exports.default = void 0;

  /**
    @hide
  */
  class EmberServer extends _server.Server {
    constructor(options) {
      // Merge models from autogenerated Ember Data models with user defined models
      if (_emberData2.hasEmberData && options.discoverEmberDataModels) {
        options.models = Object.assign({}, (0, _emberData.getModels)(), options.models);
      }

      super(options);
    }

  }

  _exports.default = EmberServer;
});